{
    'name': 'Mindlab World',
    'summary': 'Educational center and nursery lifecycle management',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'author': 'Mindlab World',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'account', 'sale_management'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/rubric_template_data.xml',
        'views/mindlab_stage_views.xml',
        'views/mindlab_category_views.xml',
        'views/mindlab_offer_views.xml',
        'views/mindlab_admission_views.xml',
        'views/mindlab_enrollment_views.xml',
        'views/evaluation_views.xml',
        'views/mindlab_attendance_views.xml',
        'wizards/attendance_batch_add_students_wizard_views.xml',
        'views/mindlab_session_log_views.xml',
        'views/mindlab_progression_views.xml',
        'views/mindlab_student_views.xml',
        'views/mindlab_account_move_views.xml',
        'views/mindlab_settings_views.xml',
        'views/mindlab_menus.xml',
    ],
    'application': True,
    'installable': True,
}
