from . import mindlab_stage
from . import mindlab_category
from . import mindlab_offer
from . import mindlab_admission
from . import mindlab_student
from . import mindlab_enrollment
from . import mindlab_attendance
from . import evaluation_template
from . import student_evaluation
from . import mindlab_progression
from . import mindlab_session_log
from . import account_move
from . import res_config_settings
